### ISSUE TITLE
Use named exports from utility modules

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7779]
This is not a formal categorization, but we have two broad categories of modules in the library:
 1. modules that export a constructor or an enum
 2. modules that export a collection of functions or constants

The first category of modules have UpperCamelCase names.  For example, [`ol/layer/VectorTile.js`](https://github.com/openlayers/openlayers/blob/3266ffc58ff50bef012af6bfd93ec6e3c5a7fe69/src/ol/layer/VectorTile.js) exports the `VectorTile` layer constructor.  To use the constructor, people can import the default export.  E.g.
```js
import VectorTile from 'ol/layer/VectorTile';
```

Enums like [`GeometryType`](https://github.com/openlayers/openlayers/blob/3266ffc58ff50bef012af6bfd93ec6e3c5a7fe69/src/ol/geom/GeometryType.js) fit into the same category.  E.g.
```js
import GeometryType from 'ol/geom/GeometryType';
// now use something like GeometryType.POINT
```

The second category of modules export just functions or constants.  For consistency, we want these to use named exports and *not* have a default export.  The `ol/proj` module is an example of this category.  When people use it, they import just what they need of the named exports.  E.g.
```js
import {toLonLat} from 'ol/proj';
```

Before the 5.0 release, we need to finish the work of adding named exports and removing the default export from these lowercase, utility modules.  As of this writing, it looks like there are 31 modules that still need reworking (based on `grep -E 'export default _([a-z]|_)+\b' -r src`):

- [x] `src/ol/net.js` (see #7780)
- [x] `src/ol/tilegrid.js` (see #7800)
- [x] `src/ol/renderer/webgl/defaultmapshader.js` (see #7788)
- [x] `src/ol/renderer/webgl/tilelayershader.js` (see #7788)
- [x] `src/ol/renderer/vector.js` (see #7800)
- [x] `src/ol/size.js` (see #7780)
- [x] `src/ol/reproj.js` (see #7780)
- [x] `src/ol/coordinate.js` (see #7800)
- [x] `src/ol/xml.js` (see #7783)
- [x] `src/ol/render/webgl/texturereplay/defaultshader.js` (see #7788)
- [x] `src/ol/render/webgl/linestringreplay/defaultshader.js` (see #7788)
- [x] `src/ol/render/webgl/circlereplay/defaultshader.js` (see #7788)
- [x] `src/ol/render/webgl/polygonreplay/defaultshader.js` (see #7788)
- [x] `src/ol/render/webgl.js` (see #7840)
- [x] `src/ol/render/canvas.js` (see #7827)
- [x ] `src/ol/render/replay.js` (see #7840)
- [x] `src/ol/tilecoord.js` (see #7791) 
- [x] `src/ol/webgl.js` (see #7840)
- [x] `src/ol/geom/flat/inflate.js` (see #7820)
- [x] `src/ol/geom/flat/deflate.js` (see #7820)
- [x] `src/ol/geom/flat/length.js` (see #7820)
- [x] `src/ol/geom/flat/textpath.js` (see #7820)
- [x] `src/ol/geom/flat/straightchunk.js` (see #7820)
- [x] `src/ol/geom/flat/simplify.js` (see #7820)
- [x] `src/ol/geom/flat/interiorpoint.js` (see #7820)
- [x] `src/ol/geom/flat/closest.js` (see #7820)
- [x] `src/ol/geom/flat/orient.js` (see #7820)
- [x] `src/ol/geom/flat/interpolate.js` (see #7820)
- [x] `src/ol/geom/flat/intersectsextent.js` (see #7820)
- [x] `src/ol/geom/flat/transform.js` (see #7820)
- [x] `src/ol/transform.js` (see #7834)

If people want to contribute to this effort, we welcome your help.  See #7745, #7764, and #7772 for a few examples.  Some suggestions for making a contribution:
 * if a named export is very generic, use a more specific name when importing (e.g. `import {add as addCoordinate} from 'ol/coordinate'`)
 * make sure to avoid any existing names when importing - the linter helps with this, but may not catch all conflicts
 * add a comment to this issue when you are starting work on one of the above modules so we can avoid any redundant efforts
 * if you run into a complicated case, ask for help here
 * maybe avoid the webgl modules if this is your first contribution

See also #7616 if you are interested in mind-numbing work of this nature.  That ticket is about renaming the remaining `_ol_Foo_` type names.

**Comment by tschaub** [comment]
Starting at the top of the list (and perhaps the easiest in the whole batch).  I'll take on `ol/net.js`.

**Comment by raiyni** [comment]
I'll do `ol/xml.js`

**Comment by tschaub** [comment]
Thanks @raiyni!.  I'll take `ol/size.js` next since `ol/net.js` was so easy.

**Comment by marcjansen** [comment]
See #7791 for ol/tilecoord. I had problems with on particular test: `createFromTemplates` in `tileurlfunction.test.js` which used to override the `hash` method with sinon. I have removed most of the test and cannot say whether this si still testing anything useful. Comments here or in the PR appreciated.

**Comment by tschaub** [comment]
I'll take on `ol/tilegrid.js` now.

**Comment by raiyni** [comment]
doing `ol/geom/flat/*`

**Comment by tschaub** [comment]
I'll start work on these:
 * `ol/render/*`

**Comment by marcjansen** [comment]
I'll do `src/ol/transform.js`

**Comment by raiyni** [comment]
time for `ol/webgl`

**Comment by raiyni** [comment]
`ol/render/webgl` next

**Comment by raiyni** [comment]
`ol/render/replay` now

**Comment by tschaub** [comment]
Wohoo!  We're done!
