### ISSUE TITLE
Replace static members with named exports

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7801]
We currently tack additional properties onto constructor functions.  For example:
```js
import Modify from 'ol/interaction/Modify';
// Modify.Event, Modify.getDefaultStyleFunction
```

Instead, where we intentionally want to export something from a module, we should do so explicitly.  Then it would be used like this:
```js
import Modify, {Event as ModifyEvent} from 'ol/interaction/Modify';
```

Where we do not use a symbol elsewhere in the library or have it marked as `@api` for public consumption, we should not export anything.

These modules need work (based on `grep -E '^[A-Z]\w+\.\w+ =' -lr src`):
 - [x] `ol/RotationConstraint.js` (see #7828)
 - [x] `ol/Observable.js` (see #7868)
 - [x] `ol/proj/Units.js` (see #7894)
 - [x] `ol/CenterConstraint.js` (see #7828)
 - [x] `ol/renderer/canvas/VectorTileLayer.js` (see #7823)
 - [x] `ol/renderer/Map.js` (see #7823)
 - [x] `ol/Feature.js` (see #7823)
 - [x] `ol/source/OSM.js` (see #7894)
 - [x] `ol/source/WMTS.js` (see #7894)
 - [x] `ol/source/Tile.js` (see #7894)
 - [x] `ol/source/Vector.js` (see #7894)
 - [x] `ol/source/Raster.js` (see #7894)
 - [x] `ol/source/BingMaps.js` (see #7894)
 - [x] `ol/source/Stamen.js` (see #7894)
 - [x] `ol/source/Image.js` (see #7894)
 - [x] `ol/source/TileImage.js` (see #7894)
 - [x] `ol/source/ImageMapGuide.js` (see #7894)
 - [x] `ol/Object.js` (see #7894)
 - [x] `ol/render/canvas/TextReplay.js`
 - [x] `ol/render/canvas/ReplayGroup.js`
 - [x] `ol/style/Style.js` (see #7880)
 - [x] `ol/style/IconImage.js` (see #7872)
 - [x] `ol/TileRange.js` (see #7868)
 - [x] `ol/layer/Layer.js` (see #7823)
 - [x] `ol/geom/SimpleGeometry.js` (see #7855)
 - [x] `ol/structs/PriorityQueue.js` (see #7861)
 - [x] `ol/format/XLink.js` (see #7823)
 - [x] `ol/format/GMLBase.js` (see #7855)
 - [x] `ol/format/XSD.js` (see #7855)
 - [x] `ol/format/WFS.js` (see #7823)
 - [x] `ol/View.js` (see #7868)
 - [x] `ol/pointer/PointerEvent.js` (see #7888)
 - [x] `ol/pointer/PointerEventHandler.js` (see #7888)
 - [x] `ol/pointer/MouseSource.js` (see #7888)
 - [x] `ol/pointer/TouchSource.js` (see #7888)
 - [x] `ol/events/Event.js` (see #7851)
 - [x] `ol/ImageTile.js` (see #7855)
 - [x] `ol/interaction/Snap.js` (see #7894)
 - [x] `ol/interaction/DragBox.js` (see #7874)
 - [x] `ol/interaction/KeyboardPan.js` (see #7855)
 - [x] `ol/interaction/Translate.js` (see #7894)
 - [x] `ol/interaction/Interaction.js` (see #7894)
 - [x] `ol/interaction/MouseWheelZoom.js` (see #7855)
 - [x] `ol/interaction/Extent.js` (see #7874)
 - [x] `ol/interaction/DragAndDrop.js` (see #7855)
 - [x] `ol/interaction/Select.js` (see #7894)
 - [x] `ol/interaction/Pointer.js` (see #7894)
 - [x] `ol/interaction/KeyboardZoom.js` (see #7855)
 - [x] `ol/interaction/Draw.js` (see #7874)
 - [x] `ol/interaction/DoubleClickZoom.js` (see #7855)
 - [x] `ol/interaction/Modify.js` (see #7894)
 - [x] `ol/control/OverviewMap.js` (see #7851)
 - [x] `ol/control/MousePosition.js` (see #7851)
 - [x] `ol/control/ZoomSlider.js` (see #7851)
 - [x] `ol/control/Rotate.js` (see #7851)
 - [x] `ol/control/ScaleLine.js` (see #7851)
 - [x] `ol/control/Attribution.js` (see #7851)
 - [x] `ol/control/FullScreen.js` (see #7851)
 - [x] `ol/Collection.js` (see #7851)
 - [x] `ol/ResolutionConstraint.js` (see #7828)

**Comment by tschaub** [comment]
We've got a lot of tests that mock functions on `Interaction` that are going to require reworking.

**Comment by tschaub** [comment]
Done!
