### ISSUE TITLE
Remove "private" static members

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7802]
We have a lot of things like `Foo.bar_`.  If a property is private, it should not be exported.  So instead of tacking these properties onto the constructor, they can be declared separately and not exported.

It looks like these modules need work (based on `grep -E '(^|\s)[A-Z]\w+\.\w+_ =' -lr src`):

- [x] `ol/control/FullScreen.js` (see #7803)
- [x] `ol/control/MousePosition.js` (see #7803)
- [x] `ol/control/ScaleLine.js` (see #7803)
- [x] `ol/control/ZoomSlider.js` (see #7803)
- [x] `ol/format/EsriJSON.js` (see #7803)
- [x] `ol/format/GML2.js` (see #7803)
- [x] `ol/format/GML3.js` (see #7803)
- [x] `ol/format/GMLBase.js` (see #7803)
- [x] `ol/format/GPX.js` (see #7803)
- [x] `ol/format/KML.js` (see #7803)
- [x] `ol/format/MVT.js` (see #7814)
- [x] `ol/format/OSMXML.js` (see #7814)
- [x] `ol/format/OWS.js` (see #7814)
- [x] `ol/format/WFS.js` (see #7814)
- [x] `ol/format/WKT.js` (see #7814)
- [x] `ol/format/WMSCapabilities.js` (see #7803)
- [x] `ol/format/WMSGetFeatureInfo.js` (see #7814)
- [x] `ol/format/WMTSCapabilities.js` (see #7803)
- [x] `ol/geom/GeometryCollection.js` (see #7805)
- [x] `ol/interaction/DragAndDrop.js` (see #7817)
- [x] `ol/interaction/DragBox.js` (see #7817)
- [x] `ol/interaction/DragPan.js` (see #7817)
- [x] `ol/interaction/DragRotate.js` (see #7817)
- [x] `ol/interaction/DragRotateAndZoom.js` (see #7817)
- [x] `ol/interaction/Draw.js` (see #7817)
- [x] `ol/interaction/Extent.js` (see #7817)
- [x] `ol/interaction/Modify.js` (see #7817)
- [x] `ol/interaction/MouseWheelZoom.js` (see #7817)
- [x] `ol/interaction/PinchRotate.js` (see #7817)
- [x] `ol/interaction/PinchZoom.js` (see #7817)
- [x] `ol/interaction/Select.js` (see #7817)
- [x] `ol/interaction/Snap.js` (see #7817)
- [x] `ol/interaction/Translate.js` (see #7817)
- [x] `ol/Object.js` (see #7817)
- [x] `ol/render/canvas/ReplayGroup.js` (see #7805)
- [x] `ol/render/webgl/LineStringReplay.js` (see #7805)
- [x] `ol/render/webgl/ReplayGroup.js` (see #7805)
- [x] `ol/renderer/Map.js`(see #7805)
- [x] `ol/source/Image.js` (see #7817)
- [x] `ol/source/ImageWMS.js` (see #7817)
- [x] `ol/source/Raster.js` (see #7817)
- [x] `ol/source/TileDebug.js` (see #7817)
- [x] `ol/source/TileUTFGrid.js` (see #7817)
- [x] `ol/source/Zoomify.js` (see #7817)
- [x] `ol/style/Style.js` (see #7817)
- [x] `ol/style/Text.js` (see #7817)
- [x] `ol/tilegrid/TileGrid.js` (see #7817)
- [x] `ol/View.js` (see #7817)
- [x] `ol/webgl/Context.js` (see #7815)

**Comment by tschaub** [comment]
I'll work on the controls now.
