### ISSUE TITLE
Get rid of the olx namespace and simplify typedefs

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#7838]
By using the latest version of [babel-plugin-jsdoc-closure](https://npmjs.com/babel-plugin-jsdoc-closure), we can now introduce JSDoc path types with [module identifiers](http://usejsdoc.org/howto-commonjs-modules.html#module-identifiers) and JSDoc [typedefs](http://usejsdoc.org/tags-typedef.html).

The work we have ahead of us here will wrap up #7608, and simplifies the approach started in #7609.

### Option object literals

We no longer need to duplicate option object literals for constructors and methods. With JSDoc typedefs, we can define and document all options, and can inline them later into the constructor documentation with a simple [JSDoc plugin](https://github.com/openlayers/closure-es-modules/blob/master/jsdoc-inline-options.js).

For options that are only used for a constructor (and its subclasses, like e.g. for `PluggableMap` and `Map`) or a method (and its subclasses, like e.g. `FeatureFormat#readFeatures`), the typedef can be placed in the file that implements the topmost class in the hierarchy. The format is straightforward:

Snippet from `src/ol/PluggableMap.js`:
```js
/**
 * @module ol/PluggableMap
 */

/**
 * @typedef {Object} MapOptions
 * @property {ol.Collection.<ol.control.Control>|Array.<ol.control.Control>|undefined} controls
 * Controls initially added to the map. If not specified,
 * {@link ol.control.defaults ol.control.defaults()} is used.
 * @property {number} [pixelRatio=window.devicePixelRatio] The ratio between physical
 * pixels and device-independent pixels (dips) on the device.
 * (...)
 */

/**
 * @constructor
 * @param {module:ol/PluggableMap~MapOptions} options Map options.
 */
const PluggableMap = function(options) {
  // ...
}
```

Also note that JSDoc and the plugin can handle optional properties and defaults. See the `pixelRatio` property above. Its type will be transformed to `(undefined|number)` by the plugin, and JSDoc will list the default value `window.devicePixelRatio`.

Other typedefs, like `olx.FrameState` or those from `src/ol/typedefs.js`, can go to appropriate places (e.g. `src/ol/PluggableMap.js` for `olx.FrameState`), using the same syntax.

### Referencing types in other files

When using types in different files, they are referenced using module types.

Snippet from `src/ol/Map.js`:
```js
/**
 * @constructor
 * @extends {module:ol/PluggableMap}
 * @param {module:ol/PluggableMap~MapOptions} options Map options.
 */
const Map = function(options) {
  // ...
}
```

### Tasks

- [x] Modify the `tasks/t.js` script from #7608 to provide typedef material
- [x] Get rid of `externs/olx.js` by moving all typedefs from there to appropriate places (or `src/types.js` if no other is appropriate).
- [x] Get rid of `src/ol/typedefs.js` by moving all typedefs from there to appropriate places (or `src/ol/types.js` if no other is appropriate)

See #7947 for progress on these tasks.

### Related efforts

Something similar will probably apply to the `oli` namespace, that needs a bit more research though. In addition to typedefs, we will need to find a simpler way to annotate events so they appear in the class documentation.

**Comment by tschaub** [comment]
For shared types, I think we'll want `src/ol/types.js` instead of `src/types.js`.  Only sources in the `src/ol` directory will be published with the package.

Perhaps we'll be able to collapse the source directory (removing `ol`).

**Comment by tschaub** [comment]
@ahocevar - for clarification, where we only use a `typedef` in a single module, will we need to use the full `module:ol/path/to/Module~Name` syntax (or is `Name` sufficient)?  In other words, will this work:
```js
/**
 * @module ol/SomeModule
 */

/**
 * @typedef {Object} Options
 * @property {string} foo The foo option.
 */

/**
 * @constructor
 * @param {Options} options The options.
 */
const Constructor = function(options) {
  // ...
}
```

**Comment by ahocevar** [comment]
We could make that work, and I had it supported in an earlier version of the jsdoc plugin in https://github.com/openlayers/closure-es-modules. But without plugin, JSDoc cannot handle that. So I decided to provide the full module path and not do something in the plugin that is not handled elsewhere.

**Comment by ahocevar** [comment]
Regarding `src/ol/types.js` (I agree that’s the appropriate place, I went a bit back on whether we need it at all. In the last pull request, I found a place for all types elsewhere, and in the end it does not matter where they are defined.

**Comment by tschaub** [comment]
> So I decided to provide the full module path and not do something in the plugin that is not handled elsewhere.

Sounds good.

**Comment by fredj** [comment]
done, closing.
