### ISSUE TITLE
Re-export constructors

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#8110]
We can make it more convenient for users to import constructors by re-exporting them from common modules.  For example, all of the control constructors can be re-exported from `ol/control`.  Internally, we will continue to import from the origin, but we can update our examples to import from these common modules.  The end result should be fewer `import` statements for users.

E.g.

Before:
```js
import Style from 'ol/style/Style';
import Stroke from 'ol/style/Stroke';
import Fill from 'ol/style/Fill';
```

After:
```js
import {Style, Stroke, Fill} from 'ol/style';
```

Some of this work may involve shuffling things around to avoid cyclic dependencies (e.g. `iconImageCache` should be moved to `ol/style/IconImageCache~shared` or similar).

Here is a list of the work to be done:

- [x] export controls from `ol/control.js` (#8111)
- [x] export formats from `ol/format.js` (#8112)
- [x] export geometries from `ol/geom.js` (#8113)
- [x] export interactions from `ol/interaction.js` (#8114)
- [x] export layers from `ol/layer.js` (#8115)
- [x] export sources from `ol/source.js` (#8116)
- [x] export styles from `ol/style.js` (#8117)
