### ISSUE TITLE
Clean up examples

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#827]
- [x] Remove markup from all `shortdesc` elements (this should be just a plain text description) #828
- [x] Add useful descriptions to all examples #828
- [ ] Use nicer data for [kml example](http://ol3js.org/en/master/examples/kml.html) (rabbit hole #829, example in #831)
